# Generated by Django 6.0.3 on 2026-04-19 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('usda_food_id', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.household')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('household', 'name')},
            },
        ),
        migrations.CreateModel(
            name='IngredientLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=6)),
                ('unit', models.CharField(choices=[('oz', 'ounce'), ('lb', 'pound'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('g', 'gram'), ('kg', 'kilogram'), ('ml', 'milliliter'), ('l', 'liter'), ('piece', 'piece'), ('clove', 'clove'), ('slice', 'slice'), ('bunch', 'bunch'), ('can', 'can')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredients.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
