# Generated by Django 6.0.3 on 2026-04-19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingredients", "0002_ingredientlink_inventory_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="calories_kcal",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="carbs_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="fat_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="ingredient",
            name="protein_g",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=7,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="ingredientlink",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="recipes.recipe",
            ),
        ),
    ]
