# Generated by Django 6.0.3 on 2026-04-19 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField(db_index=True)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=20)),
                ('custom_meal', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('meal_rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to='household.household')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meal_plans', to='recipes.recipe')),
            ],
            options={
                'ordering': ['meal_date', 'meal_type'],
                'indexes': [models.Index(fields=['household', 'meal_date'], name='meal_planne_househo_3a379c_idx'), models.Index(fields=['meal_date', 'meal_type'], name='meal_planne_meal_da_63b6c6_idx')],
                'constraints': [models.UniqueConstraint(fields=('household', 'meal_date', 'meal_type', 'recipe'), name='unique_meal_per_type')],
            },
        ),
    ]
