# Generated by Django 6.0.5 on 2026-05-31 20:04

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_household_expiring_threshold_days'),
        ('meal_planner_app', '0002_mealplan_cooked_at_sidedish'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine_preferences', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('dietary_restrictions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list)),
                ('cooking_effort', models.CharField(choices=[('quick', 'Quick (<30 min)'), ('moderate', 'Moderate (30-60 min)'), ('elaborate', 'Elaborate (>60 min)')], default='moderate', max_length=20)),
                ('servings_per_meal', models.PositiveSmallIntegerField(default=2)),
                ('excluded_ingredients', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_preferences', to='household.household')),
            ],
            options={
                'verbose_name_plural': 'meal preferences',
            },
        ),
    ]
