# Generated by Django 6.0.5 on 2026-05-31 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner_app', '0003_mealpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='ingredients',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
