# Generated by Django 6.0.6 on 2026-07-03 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_household_expiring_threshold_days'),
        ('meal_planner_app', '0004_mealplan_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_bindings', models.JSONField(blank=True, default=dict)),
                ('openrouter_api_key_override', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_settings', to='household.household')),
            ],
            options={
                'verbose_name': 'AI settings',
                'verbose_name_plural': 'AI settings',
            },
        ),
    ]
