# Generated by Django 6.0.6 on 2026-07-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner_app', '0005_aisettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisettings',
            name='usda_fdc_api_key_override',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
