#!/usr/bin/env python3
"""
YouTube Video Transcriber and Summarizer

This script takes a YouTube link, transcribes the video,
and generates a summarized document.

Usage:
    # Using the virtual environment
    /path/to/.venv/bin/python youtube_summarizer.py "https://www.youtube.com/watch?v=VIDEO_ID"
    youtube_summarizer.py "URL" -o output.md
    youtube_summarizer.py "URL" -m anthropic/claude-opus-4.5
    youtube_summarizer.py "URL" --transcript-only

Requirements:
    # First time setup (in project directory):
    python3 -m venv .venv
    source .venv/bin/activate  # or .venv/bin/activate.fish
    pip install "markitdown[youtube-transcription]" openai

    Set your OpenRouter API key as environment variable:
    export OPENROUTER_API_KEY="your-key-here"
"""

import argparse
import os
import sys
from pathlib import Path
from datetime import datetime

from markitdown import MarkItDown
from openai import OpenAI


def setup_llm_client():
    """Initialize the LLM client for summarization."""
    api_key = os.environ.get("OPENROUTER_API_KEY")
    if not api_key:
        api_key = input("Enter your OpenRouter API key: ").strip()

    return OpenAI(api_key=api_key, base_url="https://openrouter.ai/api/v1")


def transcribe_youtube(url: str) -> str:
    """Transcribe a YouTube video using MarkItDown."""
    print(
        f"[{datetime.now().strftime('%H:%M:%S')}] Fetching transcript from YouTube video..."
    )
    print(f"  URL: {url}")

    md = MarkItDown()
    result = md.convert(url)

    transcript = result.text_content
    print(
        f"[{datetime.now().strftime('%H:%M:%S')}] Retrieved {len(transcript)} characters of transcript"
    )

    return transcript


def summarize_transcript(
    transcript: str, client: OpenAI, model: str = "anthropic/claude-sonnet-4-20250514"
) -> str:
    """Summarize the transcript using an LLM."""
    print(
        f"[{datetime.now().strftime('%H:%M:%S')}] Generating summary using {model}..."
    )

    prompt = f"""You are an expert summarizer. Create a comprehensive but concise summary of the following video transcript.

Your summary should include:
1. **Video Title/Topic**: What is this video about?
2. **Key Points**: The main ideas and arguments presented (5-10 bullet points)
3. **Important Details**: Specific data, statistics, or facts mentioned
4. **Conclusions/Takeaways**: What can viewers conclude or learn from this video?

Format the output as a well-structured markdown document.

TRANSCRIPT:
---
{transcript}
---

SUMMARY:"""

    response = client.chat.completions.create(
        model=model,
        messages=[
            {
                "role": "system",
                "content": "You are a helpful research assistant that creates clear, well-structured summaries.",
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0.3,
        max_tokens=4000,
    )

    summary = response.choices[0].message.content
    print(
        f"[{datetime.now().strftime('%H:%M:%S')}] Generated summary ({len(summary)} characters)"
    )

    return summary


def create_document(url: str, transcript: str, summary: str, output_path: Path) -> None:
    """Create a formatted markdown document with transcript and summary."""
    print(
        f"[{datetime.now().strftime('%H:%M:%S')}] Creating document at {output_path}..."
    )

    document = f"""# YouTube Video Summary

**Source**: [{url}]({url})  
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Summary

{summary}

---

## Full Transcript

*Note: The following is the auto-generated transcript from the video.*

---

{transcript}

---

*Document generated by YouTube Video Transcriber and Summarizer*
"""

    output_path.write_text(document)
    print(f"[{datetime.now().strftime('%H:%M:%S')}] Document saved successfully")


def main():
    parser = argparse.ArgumentParser(
        description="Transcribe and summarize YouTube videos"
    )
    parser.add_argument("url", help="YouTube video URL")
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output file path (default: youtube_summary_YYYYMMDD_HHMMSS.md)",
    )
    parser.add_argument(
        "-m",
        "--model",
        default="anthropic/claude-sonnet-4-20250514",
        help="OpenRouter model to use for summarization",
    )
    parser.add_argument(
        "--transcript-only",
        action="store_true",
        help="Only save the transcript, skip summarization",
    )

    args = parser.parse_args()

    try:
        transcript = transcribe_youtube(args.url)

        if args.transcript_only:
            summary = "*(Summarization skipped by user request)*"
        else:
            client = setup_llm_client()
            summary = summarize_transcript(transcript, client, args.model)

        if args.output:
            output_path = Path(args.output)
        else:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            output_path = Path(f"youtube_summary_{timestamp}.md")

        create_document(args.url, transcript, summary, output_path)

        print(f"\n[SUCCESS] Output saved to: {output_path}")

    except Exception as e:
        print(f"\n[ERROR] {str(e)}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
