# Generated by Django 6.0.3 on 2026-04-19 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit', models.CharField(choices=[('oz', 'ounce'), ('lb', 'pound'), ('cup', 'cup'), ('tbsp', 'tablespoon'), ('tsp', 'teaspoon'), ('g', 'gram'), ('kg', 'kilogram'), ('ml', 'milliliter'), ('l', 'liter'), ('piece', 'piece'), ('dozen', 'dozen'), ('pack', 'pack'), ('box', 'box'), ('can', 'can'), ('bottle', 'bottle'), ('bag', 'bag')], default='piece', max_length=20)),
                ('category', models.CharField(choices=[('produce', 'Produce'), ('dairy', 'Dairy'), ('meat', 'Meat & Seafood'), ('frozen', 'Frozen'), ('pantry', 'Pantry'), ('beverages', 'Beverages'), ('condiments', 'Condiments & Sauces'), ('snacks', 'Snacks'), ('bakery', 'Bakery'), ('other', 'Other')], default='other', max_length=20)),
                ('location', models.CharField(choices=[('pantry', 'Pantry'), ('refrigerator', 'Refrigerator'), ('freezer', 'Freezer'), ('counter', 'Counter'), ('cabinet', 'Cabinet')], default='pantry', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='household.household')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['household', 'name'], name='inventory_i_househo_89815e_idx'), models.Index(fields=['household', 'expiration_date'], name='inventory_i_househo_818711_idx')],
            },
        ),
    ]
