# Generated by Django 6.0.3 on 2026-04-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="inventory/%Y/%m/%d/"
            ),
        ),
    ]
