# Generated by Django 6.0.6 on 2026-06-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcLookupUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('openfoodfacts', 'Open Food Facts'), ('upcitemdb', 'UPC Item DB')], max_length=20)),
                ('date', models.DateField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_call_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['service', '-date'], name='inventory_u_service_2a77cf_idx')],
                'unique_together': {('service', 'date')},
            },
        ),
    ]
