# Generated by Django 6.0.3 on 2026-04-19 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='expiring_threshold_days',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
