# Generated by Django 6.0.3 on 2026-04-19 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='recipes/%Y/%m/%d/')),
                ('video_url', models.URLField(blank=True)),
                ('on_hand_idea', models.BooleanField(db_index=True, default=False)),
                ('leftover_worthy', models.BooleanField(db_index=True, default=False)),
                ('needs_review', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='household.household')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['household', 'created_at'], name='recipes_rec_househo_f41e63_idx')],
            },
        ),
    ]
