# Generated by Django 6.0.6 on 2026-06-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='transcript_log',
            field=models.CharField(blank=True, help_text='Path to the saved YouTube transcript log under logs/transcripts/, if any.', max_length=512),
        ),
    ]
