# Generated by Django 6.0.6 on 2026-07-12 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_transcript_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeWatchSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], db_index=True, default='pending', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_session', to='recipes.recipe')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeWatchSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(decimal_places=3, help_text='Segment start time in seconds', max_digits=10)),
                ('end_time', models.DecimalField(decimal_places=3, help_text='Segment end time in seconds', max_digits=10)),
                ('text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='watch/%Y/%m/%d/')),
                ('step_number', models.PositiveIntegerField(blank=True, help_text='Optional best-match recipe instruction step number', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='recipes.recipewatchsession')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
