# Generated by Django 6.0.6 on 2026-07-12 14:59

import recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_watch_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipewatchsegment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=recipes.models.watch_segment_frame_path),
        ),
    ]
