# Generated by Django 6.0.3 on 2026-04-19 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("household", "0001_initial"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShoppingListWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "household",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shopping_weeks",
                        to="household.household",
                    ),
                ),
            ],
            options={
                "ordering": ["-week_start"],
            },
        ),
        migrations.CreateModel(
            name="ShoppingListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=200)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                ("unit", models.CharField(blank=True, max_length=20)),
                (
                    "category",
                    models.CharField(blank=True, default="other", max_length=50),
                ),
                ("checked", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "source_recipe",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shopping_items",
                        to="recipes.recipe",
                    ),
                ),
                (
                    "shopping_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="shopping.shoppinglistweek",
                    ),
                ),
            ],
            options={
                "ordering": ["checked", "category", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="shoppinglistweek",
            index=models.Index(
                fields=["household", "week_start"],
                name="shopping_sh_househo_7d24d8_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shoppinglistweek",
            index=models.Index(
                fields=["household", "-week_start"],
                name="shopping_sh_househo_6ce62e_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="shoppinglistweek",
            constraint=models.UniqueConstraint(
                fields=("household", "week_start"),
                name="shopping_unique_household_week",
            ),
        ),
        migrations.AddIndex(
            model_name="shoppinglistitem",
            index=models.Index(
                fields=["shopping_week", "checked"],
                name="shopping_sh_shoppin_e66c77_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="shoppinglistitem",
            index=models.Index(
                fields=["shopping_week", "category"],
                name="shopping_sh_shoppin_91573d_idx",
            ),
        ),
    ]
